name: Rebuild on Dispatch
on:
  repository_dispatch:
    types: [build]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Update to Node.js 18

      - name: Fetch and update submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive git fetch
          git submodule foreach --recursive git checkout main
          git submodule foreach --recursive git pull origin main

      - name: Upgrade npm
        run: npm install -g npm@latest # Ensure npm is at the latest version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npx quartz build

      - name: Commit and push submodule update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update submodule to latest commit"
          git push origin v4

      - name: Trigger Cloudflare Pages
        run: curl -X POST ${{ secrets.CLOUDFLARE_WEBHOOK_URL_PROD }}
