name: Rebuild on Dispatch
on:
  repository_dispatch:
    types: [build]
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Update to Node.js 18

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --recursive --remote

      - name: Force merge unrelated histories
        run: |
          git config --file .gitmodules submodule.content.branch main
          git -c submodule."content".update=merge submodule update --init --recursive --force

      - name: Upgrade npm
        run: npm install -g npm@latest # Ensure npm is at the latest version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npx quartz build

      - name: Trigger Cloudflare Pages
        run: curl -X POST ${{ secrets.CLOUDFLARE_WEBHOOK_URL_PROD }}
